# Generated by Django 3.0.7 on 2020-07-11 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriveLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=200, null=True)),
                ('file_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=100)),
                ('file_view_link', models.URLField(max_length=500, null=True)),
                ('file_icon_link', models.URLField(max_length=500, null=True)),
                ('file_created_at', models.DateTimeField(auto_now_add=True)),
                ('college_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_files_class', to='drive_files_api.Classes')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_files_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=100)),
                ('refresh_token', models.CharField(max_length=100, null=True)),
                ('token_uri', models.CharField(default='', max_length=100)),
                ('client_id', models.CharField(default='', max_length=100)),
                ('client_secret', models.CharField(default='', max_length=100)),
                ('scopes', models.CharField(default='', max_length=100)),
                ('isauthenticated', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_api', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
